version: "3.9"
services:
  tcp_server:
    build: ./tcp-server
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    environment:
      PORT: "3000"
    networks:
      - app_network
  proxy_server:
    build: ./proxy
    ports:
      - "3001:3001"
    volumes:
      - .:/code
    environment:
      PORT: "3001"
    networks:
      - app_network
  simple_website:
    build: ./simple-website
    ports:
      - "8082:80"
    volumes:
      - ./simple-website/www:/var/www/localhost

networks:
  app_network:
    driver: bridge
